#!/bin/sh
#
# ufetch-linux - tiny system info for linux

## INFO

# user is already defined
host="$(hostname)"
os="$(grep '^PRETTY_NAME=' /etc/os-release| cut -d'=' -f2 | tr -d '"')"
kernel="$(uname -sr)"
uptime="$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}' | sed -e 's/^[ \t]*//')"
packages='unknown'
shell="$(basename "${SHELL}")"
cpu="$(awk -F ': ' '/^(model name|isa|cpu model|Processor|Hardware)/ {print $2; exit}' /proc/cpuinfo)"
## TODO
ram_info="$(free -m | awk '/^Mem:/ {used=$3; total=$2; print used, total}')"
ram="$(echo $ram_info | awk '{print $2}')"
ramused="$(echo $ram_info | awk '{print $1}')"
## UI DETECTION

parse_rcs() {
        for f in "${@}"; do
                wm="$(tail -n 1 "${f}" 2> /dev/null | cut -d ' ' -f 2)"
                [ -n "${wm}" ] && echo "${wm}" && return
        done
}

rcwm="$(parse_rcs "${HOME}/.xinitrc" "${HOME}/.xsession")"

ui='unknown'
uitype='UI'
if [ -n "${DE}" ]; then
        ui="${DE}"
        uitype='DE'
elif [ -n "${WM}" ]; then
        ui="${WM}"
        uitype='WM'
elif [ -n "${XDG_CURRENT_DESKTOP}" ]; then
        ui="${XDG_CURRENT_DESKTOP}"
        uitype='DE'
elif [ -n "${DESKTOP_SESSION}" ]; then
        ui="${DESKTOP_SESSION}"
        uitype='DE'
elif [ -n "${rcwm}" ]; then
        ui="${rcwm}"
        uitype='WM'
elif [ -n "${XDG_SESSION_TYPE}" ]; then
        ui="${XDG_SESSION_TYPE}"
fi

ui="$(basename "${ui}")"

## DEFINE COLORS

# we will use git shell coloring instead
        bold='\033[1;37m'
        black='\033[0;30m'
        grey='\033[1;30m'
        red='\033[0;31m'
        green='\033[0;32m'
        yellow='\033[0;33m'
        blue='\033[0;34m'
        magenta='\033[0;35m'
        cyan='\033[0;36m'
        white='\033[0;37m'
        reset='\033[0m'
        block='\xe2\x96\x88'
## IF ON MODERN HARDWARE USE THE CHARACTER INSTEAD
##      block='█'

lc="${reset}${bold}"                # labels
nc="${reset}${bold}"                # user and hostname
ic="${reset}"                       # info
# in some terminals, black will just be black so change it to white
c0="${reset}${grey}"               # first color
c1="${reset}${white}"               # second color
c2="${reset}${yellow}"              # third color

## OUTPUT

# for proper color output we will use printf
printf "${c0}        #####            ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}       #######           ${lc}OS:        ${ic}${os}${reset}
${c0}       ##${c1}O${c0}#${c1}O${c0}##           ${lc}Kernel:    ${ic}${kernel}${reset}
${c0}       #${c2}#####${c0}#           ${lc}Uptime:    ${ic}${uptime}${reset}
${c0}     ##${c1}##${c2}###${c1}##${c0}##         ${lc}CPU:       ${ic}${cpu}${reset}
${c0}    #${c1}##########${c0}##        ${lc}Memory:    ${ic}${ramused}MiB / ${ram}MiB${reset}
${c0}   #${c1}############${c0}##       ${lc}
${c0}   #${c1}############${c0}###      ${black}${block}${block}${block}${red}${block}${block}${block}${green}${block}${block}${block}${yellow}${block}${block}${block}${blue}${block}${block}${block}${magenta}${block}${block}${block}${cyan}${block}${block}${block}${white}${block}${block}${block}
${c2}  ##${c0}#${c1}###########${c0}##${c2}#      ${grey}${block}${block}${block}${red}${block}${block}${block}${green}${block}${block}${block}${yellow}${block}${block}${block}${blue}${block}${block}${block}${magenta}${block}${block}${block}${cyan}${block}${block}${block}${white}${block}${block}${block}
${c2}######${c0}#${c1}#######${c0}#${c2}######
${c2}#######${c0}#${c1}#####${c0}#${c2}#######
${c2}  #####${c0}#######${c2}#####
${c2}
${c2}
"
